name: Update Website

on:
  repository_dispatch:
    types: [google-docs-update]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install googleapis fs-extra

      - name: Download source JSON files from Drive
        run: node .github/scripts/download-files.js
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          FOLDER_ID: ${{ github.event.client_payload.folder_id }}

      - name: Transform and merge JSON to final data.json
        run: node conversion-script.js

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/guide_data.json
          git commit -m "Update website data" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
